version: "3"
services:

  actinia:
    build:
      context: .
      dockerfile: actinia-dev/Dockerfile
    volumes:
      - ./actinia-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-data/userdata:/actinia_core/userdata
      - ./actinia-data/pgpass:/mnt/pgpass
      - ./actinia-data/geodata_dir:/mnt/geodata
      - ./actinia-data/workspace/temp_db:/actinia_core/workspace/temp_db
      - ./actinia-data/workspace/tmp:/actinia_core/workspace/tmp
      - ./actinia-data/resources:/actinia_core/resources
      - ../actinia-core:/src/actinia_core/.
      - ../actinia-example-plugin/:/src/actinia-example-plugin/.
      # - ../actinia-api:/src/actinia-api/.
      # - ../actinia-grassdata-management-plugin:/src/actinia-grassdata-management-plugin/.
      # - ../actinia-metadata-plugin/:/src/actinia-metadata-plugin/.
      # - ../actinia-module-plugin/:/src/actinia-module-plugin/.
      # - ../actinia-stac-plugin/:/src/actinia-stac-plugin/.
      # - ../actinia_statistic_plugin/:/src/actinia_statistic_plugin/.
      # - ../actinia-processing-lib:/src/actinia-processing-lib/.
      # - ../actinia-rest-lib:/src/actinia-rest-lib/.
    ports:
      - "8088:8088"
    depends_on:
      - valkey
    cap_add:
      - SYS_PTRACE
    networks:
    -   actinia-dev

  valkey:
    image: valkey/valkey:8.1-alpine
    volumes:
      - ./valkey_data:/data
    environment:
      - VALKEY_PASS_FILE=/data/config/.valkey
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/valkey.conf"
      --requirepass "$$(cat $$VALKEY_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"
    networks:
    -   actinia-dev

  postgis:
    image: postgis/postgis:14-3.2-alpine
    volumes:
      - ./postgis/postgres_data:/var/lib/postgresql/data
      - ./postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    networks:
    -   actinia-dev

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PW}
      DB_VENDOR: postgres
      DB_ADDR: postgis
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PW}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
    depends_on:
      - postgis
    networks:
    -   actinia-dev

networks:
  actinia-dev:
    ipam:
      config:
        - subnet: 172.18.0.0/16
