version: "3"
services:

  actinia:
    # build:
      # context: actinia-prod/
    image: mundialis/actinia:2.9.1
    volumes:
      - ./actinia-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-data/userdata:/actinia_core/userdata
      - ./actinia-data/pgpass:/mnt/pgpass
      - ./actinia-data/geodata_dir:/mnt/geodata
      - ./actinia-data/workspace/temp_db:/actinia_core/workspace/temp_db
      - ./actinia-data/workspace/tmp:/actinia_core/workspace/tmp
      - ./actinia-data/resources:/actinia_core/resources
    ports:
      - "8088:8088"
    depends_on:
      - redis

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
