version: "3"
services:

  actinia:
    # build:
      # context: actinia-prod/
    image: mundialis/actinia:2.6.8
    volumes:
      - ./actinia-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-data/userdata:/actinia_core/userdata
      - ./actinia-data/pgpass:/mnt/pgpass
      - ./actinia-data/geodata_dir:/mnt/geodata
      - ./actinia-data/workspace/temp_db:/actinia_core/workspace/temp_db
      - ./actinia-data/workspace/tmp:/actinia_core/workspace/tmp
      - ./actinia-data/resources:/actinia_core/resources
    ports:
      - "8088:8088"
    depends_on:
      - keydb

  keydb:
    image: keydb:alpine_x86_64_v6.3.4
    volumes:
      - ./keydb_data:/data
    environment:
      - KEYDB_PASS_FILE=/data/config/.keydb
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/keydb.conf"
      --requirepass "$$(cat $$KEYDB_PASS_FILE)"
      '
    ]
